### ISSUE TITLE
Avoid hardcoded options

### ISSUE THREAD

**Issue by arogachev** [jonasundderwolf/django-image-cropping#106] opened 2016-09-19 08:33 UTC
Some options, such as `minSize` are now hardcoded (`minSize` is set to `[5, 5]` for example). It's better to avoid that and add possibility to set it via settings.

**Comment by anrie** [comment] 2016-09-25 14:26
@arogachev I agree. That would make sense as setting. Feel free to send a PR!

**Comment by anrie** [comment] 2016-09-25 14:31
Okay, I think the issue is covered sufficiently by #105 so I am closing this.

**Closed by anrie** 2016-09-25 14:31 UTC
