### ISSUE TITLE
crop did not working on safari

### ISSUE THREAD

**Issue by kennir** [jonasundderwolf/django-image-cropping#130] opened 2018-09-30 07:16 UTC
Hi 
It did not working on the safari 12,

The image can not display after cropped

![840aad18-14f5-493d-a9c6-d92ac9c052c5](https://user-images.githubusercontent.com/876410/46254540-9e66bc80-c4c3-11e8-99b5-c5295028f241.png)

It fine On the chrome 

![47028b6b-68b2-4165-b07a-d49a66ef684c](https://user-images.githubusercontent.com/876410/46254558-c0f8d580-c4c3-11e8-884f-46eecde3645d.png)

**Comment by MRigal** [comment] 2020-05-07 07:46
Hi @kennir 
Thanks for reporting the issue!
I cannot reproduce it, as it is working on actual Safari 13. Therefore closing the issue.

**Closed by MRigal** 2020-05-07 07:46 UTC
